[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "plosiv physics"
authors = [{name = "rzbig", email = "rzbig@nomail.com"}]
dynamic = ["version", "description"]
